spring:
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/skillmonit?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USER}
  
  liquibase:
        change-log: classpath:database/liquibaseChangeLog.xml